services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # puerto AMQP
      - "15672:15672" # consola web
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - rabbitnet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # API service for WebSocket and message monitoring
  api-service:
    build: ./api
    container_name: api-service
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitnet
    environment:
      RABBITMQ_URL: amqp://admin:admin123@rabbitmq:5672
    restart: unless-stopped

  # Web GUI for monitoring messages
  rabbitmq-gui:
    build: ./rabbitmq-gui
    container_name: rabbitmq-gui
    ports:
      - "3000:80"
    networks:
      - rabbitnet
    depends_on:
      rabbitmq:
        condition: service_healthy
      api-service:
        condition: service_started

networks:
  rabbitnet:
    driver: bridge